const he = {
  'accordionInfo.noData': 'אין מידע להצגה',
  'accordionInfo.noContent': 'אין תוכן להצגה',
  'login.forgotPassword': 'שכחתי סיסמה',
  'login.forgotUserCode': 'שכחתי קוד משתמש',
  'login.enterWithPassword': 'כניסה עם סיסמה',
  'login.enterWithSMS': 'כניסה עם קוד בסמס',
  'login.idNumber': 'מספר תעודת זהות',
  'login.userCode': 'קוד משתמש',
  'login.password': 'סיסמה',
  'login.onlyNumberAndEnglishLettersEightCharacterAtleast':
    'אותיות ומספרים באנגלית, 8 תווים לפחות.',
  'login.enter': 'כניסה',
  'login.useSMS': 'קוד ב-SmS',
  'login.faceRecognition': 'זיהוי פנים',
  'login.fingerPrint': 'טביעת אצבע',
  'login.schema.incorrectDataPleaseTryAgain':
    'אחד או יותר מהנתונים לא הוזן נכון. אבל אפשר לנסות שוב..',
  'login.schema.wrongUserCodePleaseTryAgain': 'הקוד שהוזן שגוי, נסי שנית',
  'loginLayout.startProcces': 'התחל תהליך',
  'loginLayout.enterWithSMSCode': 'כניסה עם קוד ב-SMS',
  'loginLayout.identificationProcessWithSMS':
    'כדי להזדהות עם קוד ב-SMS יש לעבור תהליך זיהוי קצר',
  'loginLayout.enterWithFaceRecognition': 'כניסה בזיהוי פנים',
  'loginLayout.identificationProcessWithFaceRecognition':
    'כדי להזדהות בזיהוי פנים יש לעבור תהליך זיהוי קצר',
  'loginLayout.enterWithFingerPrint': 'כניסה עם טביעת אצבע',
  'loginLayout.identificationProcessWithFingerPrint':
    'כדי להזדהות עם טביעת אצבע יש לעבור תהליך זיהוי קצר',
  'login.SMS.PutIdNumber': 'הזנת מספר תעודת זהות',
  'login.SMS.inValidIdNumber': 'מספר תעודת זהות לא תקין',
  'login.SMS.sendOneTimeCode': 'שליחת קוד חד פעמי לנייד',
  'login.SMS.SMSCode': 'מספר קוד',
  'login.SMS.inValidSMSCode': 'הקוד שהוקלד אינו תקין, אנא נסי שנית',
  'login.SMS.continue': 'המשיכי',
  'login.SMS.PutSMSCode': 'הזנת מספר קוד שקיבלת בSMS לנייד שמסתיים ב-',
  'login.SMS.PutPhoneCode': 'הזנת מספר קוד שקיבלת בשיחת טלפון למספר שמסתיים ב-',
  'login.SMS.theCodeLastFiveMinutes': 'הקוד תקף ל-5 דק׳.',
  'login.SMS.didntGotIt': 'לא קיבלתי,',
  'login.SMS.sendAgain': 'שלחו לי שוב',
  'login.faceId.enterWithFaceId': 'כניסה בזיהוי פנים',
  'login.faceId.approveTermsOfAgreement': 'אישור תנאי שימוש',
  'login.faceId.approve': 'לאישור',
  'login.faceId.approveTermsOfUse': 'תנאי שירות',
  'login.faceId.approveDataTransfer': 'לאישור משיכת נתונים מהתיק הרפואי',
  'login.faceId.approveTerms': 'אישור תנאים',
  'login.faceId.approveTermsError': 'יש לאשר את תנאי השימוש',
  'login.faceId.youNeedToGoToYourFaceIdSetting':
    'עליך להגדיר את זיהוי הכניסה בזיהוי פנים בהגדרות המכשיר שלך',
  'login.faceId.goToYourDeviceSettings': 'עבור להגדרות המכשיר',
  'login.faceId.needHelp': 'צריכים עזרה >',
  'login.faceId.continue': 'המשיכי',
  'login.faceId.allThatLeftIsOneTimeIdendification':
    'עכשיו נשאר רק לזהות אותך, אל תדאג זה חד פעמי',
  'login.faceId.connectTheApp': 'התחברות לאפליקציה',
  'login.faceId.signUpSuccessfully': 'נרשמת בהצלחה!',
  'login.faceId.fromNowOnYouCanLoginEasily':
    'מעכשיו אפשר להנות מהתחברות קלה ופשוטה',
  'login.fingerPrint.enterWithFingerPrint': 'כניסה בטביעת אצבע',
  'login.fingerPrint.youNeedToGoToYourfingerPrintSetting':
    'עליך להגדיר את זיהוי בטביעת אצבע בהגדרות המכשיר שלך',
  'steps.toHomePage': 'לעמוד הבית',
  'TraficLight.whatIsIt': 'מה זה מבדק בשיטת הרמזור?',
  'TraficLight.howCanItHelpMyChildren': 'ואיך השיטה יכולה לעזור לילדי?',
  'TraficLight.whatsATest': 'מה זה מבדק?',
  'TraficLight.oltraSuondTest': 'בדיקת אולטרסאונד הסוקרת את האיברים של העובר.',
  'TraficLight.whatWeTest': 'מה בודקים בו?',
  'TraficLight.viaOltraSoundTest':
    'באמצעות מכשיר אולטרסאונד סוקרים את האיברים של העובר במטרה לאתר מומים וממצאים לא תקינים. הבדיקה לרוב נעשית בגישה בטנית.',
  'TraficLight.howTheResultEffects': 'איך משפיעות התוצאות?',
  'TraficLight.atTheWomenHospital':
    'במרכזים לבריאות האישה של כללית או באופן פרטי.',
  'Home.youCanFollowAfterChildProgress':
    'ניתן לעקוב באפליקציה אחר ההתפתחות ילדיכם/ילדך ביומן ההתפתחותי ולבצע פעולות למול מרפאת התפתחות הילד',
  'Home.hello': 'שלום',
  'Home.generalInfo': 'מידע כללי',
  'ChildHome.myTests': 'המבדקים שלי',
  'ChildHome.myOlderTests': 'מבדקים קודמים',
  'ChildHome.allMyTests': 'לכל המבדקים >',
  'ChildHome.youCanDoThisAyHome': 'אפשר גם בבית',
  'ChildHome.formMoreExercises': 'לעוד תרגילים >',
  'ChildHome.commonQuestions': 'שאלות נפוצות',
  'ChildHome.forMoreQuestions': 'לעוד שאלות >',
  'ChildHome.removeMemo': 'להסרת תזכורת',
  'ChildHome.nextTest': 'המבדק הבא',
  'questionnaire.next': 'הבא',
  'questionnaire.prev': 'הקודם',
  'questionnaire.submit': 'סיום ושלח',
  'questionnaire.toHomePage': 'לעמוד הבית',
};

export default he;
